### ISSUE TITLE
TConfig节点配置文件不生效

### ISSUE THREAD

**Issue by LexaTang** [TarsCloud/K8SFramework#13]
## 版本
https://raw.githubusercontent.com/TarsCloud/K8SFramework/master/charts/tarscontroller-1.4.0.tgz
https://raw.githubusercontent.com/TarsCloud/K8SFramework/master/charts/tarsframework-1.4.0.tgz

## server-config.yaml

```
apiVersion: k8s.tars.io/v1beta2
app: ***
configContent: |-
  {}
configName: test.json
kind: TConfig
metadata:
  labels:
    tars.io/ConfigName: test.json
    tars.io/PodSeq: m
    tars.io/ServerApp: ***
    tars.io/ServerName: ***
  name: f8862d3342e20ceb030fbe438666ae62
  namespace: tars
podSeq: m
server: ***
```

## pod-config.yaml
```
apiVersion: k8s.tars.io/v1beta2
app: ***
configContent: |
  {"a": 1}
configName: test.json
kind: TConfig
metadata:
  labels:
    tars.io/ConfigName: test.json
    tars.io/PodSeq: '1'
    tars.io/ServerApp: ***
    tars.io/ServerName: ***
  name: eab62c6708825cdf6458ed248270cbf5
  namespace: tars
podSeq: '1'
server: ***
```

# 实际结果
在pod-1中cat 配置文件`test.json`得到
```
{}
```

# 预期结果
在pod-1中cat 配置文件`test.json`得到
```
{"a": 1}
```
