### ISSUE TITLE
tars-elasticsearch 启动失败

### ISSUE THREAD

**Issue by beastpu** [TarsCloud/K8SFramework#9]
elasticsearch 挂载失败
MountVolume.NewMounter initialization failed for volume "tars-dev-data-tars-elasticsearch-9ba1c2b" : path "/usr/local/app/tars/host-mount/tars-dev/tars.elasticsearch/data" does not

**Comment by zhixiongdu027** [comment]
你好,这个错误信息 表明在为 tars-elasticsearch 分配磁盘空间时失败了.

方便 提供下 TServer/Statefulset /PVC 信息吗
你可以分别执行:
```shell
 kubectl get tserver -n tars-dev tars-elasticsearch -o yaml
 kubectl get statefulset -n tars-dev tars-elasticsearch -o yaml
 kubectl get pvc -n tars-dev -o yaml
``` 
获取到信息

**Comment by beastpu** [comment]
k8s version: 1.21

kubectl get tserver -n tars-dev tars-elasticsearch -o yaml
```
apiVersion: k8s.tars.io/v1beta2
kind: TServer
metadata:
  annotations:
    meta.helm.sh/release-name: tarsframework
    meta.helm.sh/release-namespace: tars-dev
  labels:
    app.kubernetes.io/managed-by: Helm
    tars.io/ServerApp: tars
    tars.io/ServerName: elasticsearch
    tars.io/SubType: normal
  name: tars-elasticsearch
  namespace: tars-dev
spec:
  app: tars
  important: 3
  k8s:
    abilityAffinity: AppOrServerPreferred
    daemonSet: false
    env:
    - name: discovery.type
      value: single-node
    hostIPC: false
    hostNetwork: false
    imagePullPolicy: Always
    launcherType: background
    mounts:
    - mountPath: /usr/share/elasticsearch/data
      name: data
      readOnly: false
      source:
        tLocalVolume:
          gid: "0"
          mode: "755"
          uid: "1000"
    notStacked: false
    podManagementPolicy: Parallel
    replicas: 1
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  normal:
    ports:
    - isTcp: true
      name: http
      port: 9200
  release:
    id: latest
    image: tarscloud/tars.elasticsearch:latest
    secret: ""
    time: "2022-05-09T02:14:28Z"
  server: elasticsearch
  subType: normal
```

kubectl get statefulset -n tars-dev tars-elasticsearch -o yaml
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    tars.io/ServerApp: tars
    tars.io/ServerName: elasticsearch
  name: tars-elasticsearch
  namespace: tars-dev
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      tars.io/ServerApp: tars
      tars.io/ServerName: elasticsearch
  serviceName: tars-elasticsearch
  template:
    metadata:
      creationTimestamp: null
      labels:
        tars.io/ServerApp: tars
        tars.io/ServerID: latest
        tars.io/ServerName: elasticsearch
      name: tars-elasticsearch
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: tars.io/ability.tars-dev.tars-elasticsearch
                operator: Exists
            weight: 60
          - preference:
              matchExpressions:
              - key: tars.io/ability.tars-dev.tars
                operator: Exists
            weight: 30
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tars.io/node.tars-dev
                operator: Exists
      containers:
      - env:
        - name: discovery.type
          value: single-node
        image: tarscloud/tars.elasticsearch:latest
        imagePullPolicy: Always
        name: tars-elasticsearch
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
           name: data
        - mountPath: /etc/localtime
          name: host-timezone
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-timezone
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        tars.io/LocalVolume: data
        tars.io/ServerApp: tars
        tars.io/ServerName: elasticsearch
      name: data
      namespace: tars-dev
      ownerReferences:
      - apiVersion: k8s.tars.io/v1beta2
        blockOwnerDeletion: true
        controller: true
        kind: TServer
        name: tars-elasticsearch
        uid: 928580da-9016-4f63-8ab0-16b0f12bc179
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G
      selector:
        matchLabels:
          tars.io/LocalVolume: data
          tars.io/ServerApp: tars
          tars.io/ServerName: elasticsearch
      storageClassName: tars-storage-class
      volumeMode: Filesystem
    status:
      phase: Pending

```

kubectl get pvc -n tars-dev -o yaml
```
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      tars.io/LocalVolumeGID: "0"
      tars.io/LocalVolumeMode: "755"
      tars.io/LocalVolumeUID: "1000"
    labels:
      tars.io/LocalVolume: data
      tars.io/ServerApp: tars
      tars.io/ServerName: elasticsearch
    name: data-tars-elasticsearch-0
    namespace: tars-dev
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1G
    selector:
      matchLabels:
        tars.io/LocalVolume: data
        tars.io/ServerApp: tars
        tars.io/ServerName: elasticsearch
    storageClassName: tars-storage-class
    volumeName: tars-dev-data-tars-elasticsearch-2017ed07
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      tars.io/LocalVolumeGID: "0"
      tars.io/LocalVolumeMode: "755"
      tars.io/LocalVolumeUID: "0"
    labels:
      tars.io/LocalVolume: remote-log-dir
      tars.io/ServerApp: tars
      tars.io/ServerName: tarslog
    name: remote-log-dir-tars-tarslog-0
    namespace: tars-dev
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1G
    selector:
      matchLabels:
        tars.io/LocalVolume: remote-log-dir
        tars.io/ServerApp: tars
        tars.io/ServerName: tarslog
    storageClassName: tars-storage-class
    volumeName: tars-dev-remote-log-dir-tars-tarslog-2017ed07

```
